### PR TITLE
add an aion_inv to network_module and use this to replace divides

### PR DESCRIPTION
**Pull request by zingale**
this is tested here:

http://bender.astro.sunysb.edu/Microphysics/test-suite/test-suite-gfortran/2016-11-28/index.html

only 1 test has high errors, test_react-ctest -- not sure what the issue is there, but the changes are minimal.

### CODE REVIEW

**Comment by dwillcox** [comment]
Is this the right link to the test? On this link, I see a lot of failures and test_react-ctest did not compile.

**Comment by zingale** [comment]
http://bender.astro.sunysb.edu/Microphysics/test-suite/test-suite-gfortran/2016-11-28-001/index.html

**Comment by dwillcox** [comment]
Thanks! I'm not sure what is going wrong with test_react-ctest ... 

It only has the reaction C12 + He4 -> O16 though and the integration time is long enough to arrive at X(C12) < X_small. I suspect that could make the output more sensitive to the additional roundoff.

**Comment by dwillcox** [comment]
But I looked at all the source changes, and I agree they are minimal and, beyond roundoff, shouldn't make a difference.

**Comment by dwillcox** [comment]
Following up, if I change `inputs_reaclib_ctest` so that the integration time is only 1.0e-6 seconds instead of 1.0e-1 seconds, then fcompare gives the following between the `test_react` outputs for development and aioninv (before the merge):

```
            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------
 level =  1
 density                            0.000000000               0.000000000    
 temperature                        0.000000000               0.000000000    
 Xnew_helium-4                      0.000000000               0.000000000    
 Xnew_carbon-12                     0.000000000               0.000000000    
 Xnew_oxygen-16                     0.000000000               0.000000000    
 Xold_helium-4                      0.000000000               0.000000000    
 Xold_carbon-12                     0.000000000               0.000000000    
 Xold_oxygen-16                     0.000000000               0.000000000    
 wdot_helium-4                      0.000000000               0.000000000    
 wdot_carbon-12                     0.000000000               0.000000000    
 wdot_oxygen-16                     0.000000000               0.000000000    
 rho_Hnuc                           0.000000000               0.000000000    
 PLOTFILES AGREE
```

Which supports my previous assertion that the difference for the ctest network is its vulnerability to roundoff accumulation once X_C12 < X_small. In any case, the ctest results do not indicate a problem with the aioninv changes.

**Pull request merged**
